### ISSUE TITLE
Coveralls posting coverage reports multiple times

### ISSUE THREAD

**Issue by gempir** [lemurheavy/coveralls-public#1095]
Coveralls seems to post a bit too much. In this PR:

https://github.com/gempir/go-twitch-irc/pull/24

It posted 4 times and 4 times the same commit. 

Same Issue here https://github.com/gempir/go-twitch-irc/pull/18 but there 3 times.

**Comment by ArtemBernatskyy** [comment]
Same for me https://github.com/dimagi/django-prbac/pull/42

**Comment by bytewalls** [comment]
Sorry for the delay in response, your issue did not go unheard!

This seemed to be a common race condition issue with parallel builds, we have released a fix for this. Please do let us know if you see it again!

**Comment by gempir** [comment]
@bytewalls This is not fixed! Checkout my latest PR on my own Repo. https://github.com/gempir/go-twitch-irc/pull/28

The commits are the exact same. So i don't know why it's posting 4x

**Comment by chuckdumont** [comment]
@joroshiba - I'm having the same problem with my open source project.  I tried accessing the link you provided on coveralls.zendesk.com, however, I'm not able to access it because I don't have credentials to log in and the site apparently does not offer a self-registration option.  Can you please provide the relevant information where it is accessible to all?  Thanks.

**Comment by jeffrey-hokanson** [comment]
Trying to solve the same problem, I managed to find what I think is the same documentation: https://docs.coveralls.io/parallel-build-webhook

These instructions have successfully cleared up this issue for me.
