### ISSUE TITLE
500 Build processing error. while reporting - Bitbucket repos

### ISSUE THREAD

**Issue by lsanders** [lemurheavy/coveralls-public#1322]
Same behavior as #1317

**Comment by lsanders** [comment]
Hey guys,

Should we expect to continue having bitbucket integration issues? Is it such a small percentage of your customer base that you don't have it actively monitored (https://github.com/lemurheavy/coveralls-public/issues/1322)?

**Comment by sairathb** [comment]
This is turning out to be a real issue in our dev environment. We are facing the same issue

**Comment by nickmerwin** [comment]
Hi @lsanders and @sairathb fix coming shortly.

**Comment by nickmerwin** [comment]
@lsanders could you try another build now please?

**Comment by lsanders** [comment]
Still failing, @nickmerwin

**Comment by herbertrlee** [comment]
Also experiencing this issue.

**Comment by tym-network** [comment]
Same here:
`Bad response: 500 {"message":"Build processing error.","error":true,"url":""}`

**Comment by ZeeshanGhalib** [comment]
We are having the same issue.  Unable to upload report from maven.
Get the following exception:

[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project gis-parent: I/O operation failed: Report submission to Coveralls API failed with HTTP status 500: Internal Server Error (Coveralls API internal error) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project gis-parent: I/O operation failed
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: I/O operation failed
at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.execute(CoverallsReportMojo.java:259)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
... 20 more
Caused by: java.io.IOException: Report submission to Coveralls API failed with HTTP status 500: Internal Server Error (Coveralls API internal error)
at org.eluder.coveralls.maven.plugin.httpclient.CoverallsClient.parseResponse(CoverallsClient.java:108)
at org.eluder.coveralls.maven.plugin.httpclient.CoverallsClient.submit(CoverallsClient.java:85)
at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.submitData(CoverallsReportMojo.java:400)
at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.execute(CoverallsReportMojo.java:254)
... 22 more
Caused by: java.io.IOException: Coveralls API internal error
at org.eluder.coveralls.maven.plugin.httpclient.CoverallsClient.parseResponse(CoverallsClient.java:97)
... 25 more

**Comment by ZeeshanGhalib** [comment]
Hello @nickmerwin 
Any update on this issue?

**Comment by nickmerwin** [comment]
Hi @ZeeshanGhalib, we've confirmed with @lsanders that the issue has been resolved. Closing this, for now, please let me know if your next build fails.

Thanks!

**Comment by tym-network** [comment]
Hi @nickmerwin,

We still have the issue on our side.
We are using https://github.com/nickmerwin/node-coveralls to call the API with an lcov.info file as the input and a `.coveralls.yml` file at the root of the repository to give the repo token (I checked, it's the right one).

It doesn't work on Bitbucket Pipelines nor on my local environment.

Error is still 
```
Bad response: 500 {"message":"Build processing error.","error":true,"url":""}
```

It worked well until June 26th (2:37PM UTC), day of the last build. 

Any idea where the problem might come from?

**Comment by nickmerwin** [comment]
Hi @tym-network could you tell me the name of the repo in question, please?

**Comment by tym-network** [comment]
Sure, it's a private repo, accessible here: https://coveralls.io/bitbucket/GuestToGuestTeam/guesttoguest

**Comment by nickmerwin** [comment]
@tym-network ok it looks like the user that added that repo no longer has access to it on Bitbucket, could you email us at support@coveralls.io so we can arrange to have it reassigned to a new user, please?
