### ISSUE TITLE
`504` Gateway Timeouts on Coverage Uploads (Tracking Issue)

### ISSUE THREAD

**Issue by Slach** [lemurheavy/coveralls-public#1824]
look details in https://github.com/Slach/clickhouse-dump/actions/runs/18029504406/job/51303534182#step:6:167

```
 v0.6.17

📄 Using coverage file: coverage.out
  ·job_flag: run-18029504406
🚀 Posting coverage data to https://coveralls.io/api/v1/jobs
HTTP error:
---
Error: Gateway Timeout (504)
```

**Comment by pgvishnuram** [comment]
we are also observing the same for the past 6 hours

**Comment by ehuelsmann** [comment]
CloudFlare locations Dallas and Amsterdam both report 504s for me, consistently.

**Comment by eonarheim** [comment]
Same here in Minneapolis, 504s since last night 8:40pm central US

**Comment by afinetooth** [comment]
All, Thank you for reporting. The issue was resolved around `6:15am PDT`.

We are actively monitoring, and will continue working on mitigations until we can put an end to these. 

You can track status here:
https://status.coveralls.io/ ([current incident](https://status.coveralls.io/incidents/qrwpyt8h4vf1))

**Two things**:

1. If you are experiencing `put 504s`—in particular `504` errors of coverage uploads, please report in [this issue](https://github.com/lemurheavy/coveralls-public/issues/1824); and you can follow the same issue for updates. We'll do our best to circle back here and other issues. 
2. The most helpful report details, right now, are a **timestamp**, **or at least timeframe**, on your error, and any **Cloudflare Ray ID** you may have received with it.

---

**References**:
- Tracking issue (>>THIS ISSUE<<): https://github.com/lemurheavy/coveralls-public/issues/1824
- Status Page: https://status.coveralls.io/
- Incident: https://status.coveralls.io/incidents/qrwpyt8h4vf1

**Comment by paulromano** [comment]
I'm still seeing 504s sporadically, e.g., here's one that I just got:
https://github.com/openmc-dev/openmc/actions/runs/18198604615/job/51811431543

**Comment by afinetooth** [comment]
Thanks for reporting, @paulromano.

We've applied mitigations over the past few days that have significantly reduced these `504s`, but during our overnight (pre 6am PDT), where they are addresses by automations, we still aren't able to recover from every case due to the nature of the massively parallel requests. It takes an effective 15-20 min before the automation resolves the environment conditions on specific servers that are causing the timeouts.

We continue to work on this, so I'm hopeful "sporadic" will soon becomes "infrequent" -> "rare" -> "very rare" -> "never". That's the goal.

**Comment by lrivkin** [comment]
Experiencing elevated 504s today for many builds between Friday, October 3rd, 2025 at 20:15:05 UTC and now (Friday, October 3rd, 2025 at 21:50:31 UTC)

**Comment by oleibman** [comment]
I have mentioned this in the other ticket, and I hate to pile on, but, nothing has been working, not even a simple attempt to view coveralls.io, for at least 2 hours, and, since you are on PDT this is your working hours, not overnight.

**Comment by yaleman** [comment]
Seeing it also from Australia Sat Oct  4 23:37:11 UTC 2025, website is down as well

website, since the coverage tool doesn't report ray IDs

```
Ray ID: 9890467d3de25e8f
Your IP address: 2403:580b::<snip>
Error reference number: 504
Cloudflare Location: Brisbane
```

**Comment by afinetooth** [comment]
@lrivkin @oleibman Yes, we did have an incident during our Friday evening, apologies; and I do see that two (2) of our servers lost comms _prior_ to our official evening & weekend (6pm PDT Fri). 

We had an all-hands offsite, which is why our weekend started earlier than normal. If we'd been in the office or someone had been on-call we would have caught it. Sorry about the timing on that. We'll try to do better when things like that occur.

**Comment by afinetooth** [comment]
@yaleman Thanks for your report. 

I see one server down in that timeframe: We caught it after it lost comms at about 5:33PM PDT and it was restored by 5:36PM PDT, but it's hard to say how long it was in error state before that. Your timing suggests up to an hour before, starting around 4:30PM PDT. 

We are trying to improve our recovery procedure to further mitigate these over our weekends until we can fully address the root cause. Right now we rely on built-in health checks but it sounds like those may need to be shortened or replaced with a more granular polling mechanism. 

One server being down is a shame because it suggests that, at that time, there should have been three others available to serve your requests. But if you got a `504` for separate request(s), it suggests other servers may have been in error states that didn't rise to the level of our trigger. 

We'll try to do better for this coming weekend.

**Comment by yaleman** [comment]
Thanks @afinetooth I totally appreciate I'm using a free service, it's a good one!

**Comment by simsdee14-alt** [comment]
https://github.com/lemurheavy/coveralls-public/issues/1824

**Comment by hoffm** [comment]
Hello! I'm seeing 504s on job uploads.

```
  v0.6.17

📄 Using coverage file: coverage.out
🚀 Posting coverage data to https://coveralls.io/api/v1/jobs
HTTP error:
---
Error: Gateway Timeout (504)
```

Loading the coveralls.io, I also get an error page with this data:

```
The web server reported a gateway time-out error.

Ray ID: 98c6bfd4696ffbf2
Your IP address: [snip]
Error reference number: 504
Cloudflare Location: Newark
```

**Comment by asoftwareguy** [comment]
We are seeing 504s in coverage uploads today as well.

<div class="cf-error-details cf-error-504">
  <h1>Gateway time-out</h1>
  <p>The web server reported a gateway time-out error.</p>
  <ul>
    <li>Ray ID: 98c6a89ceac84871</li>
    <li>Your IP address: XXXXXXXXXX</li>
    <li>Error reference number: 504</li>
    <li>Cloudflare Location: Dallas</li>
  </ul>
</div>

**Comment by mathieuboudreau** [comment]
Same for us in AxonDeepSeg: https://github.com/axondeepseg/axondeepseg/actions/runs/18408738825/job/52457499904?pr=935

**Comment by afinetooth** [comment]
Thanks @simsdee14-alt @hoffm @asoftwareguy @mathieuboudreau 

Issue is **resolved**. Sorry we missed the early signs. We are **monitoring**:
https://status.coveralls.io/

We are also continuing to adjust our alerting system so we can catch these eariler.

**Comment by afinetooth** [comment]
**Update**:
We performed an infrastructure upgrade this week that we believe will eliminate all `504s` except some due to outlier-sized data inherent to specific projects and files.

We completed the upgrades yesterday and have been monitoring for the past 18+ hrs with zero occurrences of `504` errors.

We are now especially keen to hear any new reports of `504s` so please let us know if you experience one. 

Thanks for your patience.
