### ISSUE TITLE
Source Not Available

### ISSUE THREAD

**Issue by jongillham** [lemurheavy/coveralls-public#375]
I get the following message when I want to see the code coverage of my files:

The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.

This happened after I changed my Github username to an organisation.
I have tried removing OAuth credentials and deleting my Coveralls account with no success.

A build can be seen at https://coveralls.io/builds/1264067

How can I see my files with coverage info again?

**Comment by dansomething** [comment]
I'm experiencing this same issue. I tried revoking the applications on Github and logging out and back in to reauthorize. I also tried removing my account, but that didn't work either.

Here's an example file: https://coveralls.io/files/415905275

What else can I try?

**Comment by zeehio** [comment]
Hi, I was experiencing this issue. I tried removing coveralls from the authorized applications at Github and adding it again and the issue persisted.
At the end I fixed it by following these steps:

1. Login https://coveralls.io/
2. Go to "Pro sign up"  https://coveralls.io/sign-up
3. Click on "Resync repos" at the top of the page. https://coveralls.io/refresh?private=true
4. Authorise

I hope this instructions help future readers of this thread. :-)

**Comment by fommil** [comment]
:+1: I'm getting the same issue. I tried @zeehio's approach but "Authorize" was never requested. So I logged out of coveralls, revoked all tokens on github, logged back in to coveralls and authorized. Still failing.

**Comment by fommil** [comment]
ok, this magically started working again for me.

**Comment by dansomething** [comment]
It eventually worked itself out for me too.

**Comment by PikachuEXE** [comment]
Confirmed Visting https://coveralls.io/refresh?private=true alone 
fixed my "Source Not Available" problem

**Comment by remram44** [comment]
I'm having this problem. The repository is public, I don't understand how coveralls could fail to get the file. I did log out/in, I even tried deleting the application from Github and re-adding it by logging in. No change, can't see any file.

**Comment by prologic** [comment]
Hmmm also having the same issue
and following @zeehio instructions
with no improved effect.

**Comment by blegat** [comment]
We am having the same issue on a public repository; see https://github.com/JuliaOpt/JuMP.jl/issues/869

**Comment by blegat** [comment]
This is fixed now for JuliaOpt/JuMP.jl, I don't know what fixed it though.

**Comment by Bilge** [comment]
I'm [still having this problem](https://coveralls.io/builds/10615750/source?filename=src%2FNet%2FSoap%2FSoapConnector.php).

**Comment by remram44** [comment]
Just switch to codecov like everybody else :wink:

**Comment by brendanlong** [comment]
I'm still running into this same issue (after renaming a repo), and the workarounds above don't work since I can't log in (due to the infinite auth loop).
