### ISSUE TITLE
Travis error: 422 - Couldn't find a repository matching this job

### ISSUE THREAD

**Issue by TomSeldon** [lemurheavy/coveralls-public#888]
I have a public GitHub repo (https://github.com/boxuk/commit-message-checker), and I've enabled it on Coveralls.io.

I'm generating Coverage reports using Istanbul and piping the resultant lcov file to the `coveralls` Node module, i.e.

`cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js`

This *always* fails with the below error:

```
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

Am I doing anything wrong? Everything looks correct on the Coveralls.io side, and I've followed the docs correctly as far as I can see.

**Comment by MarcL** [comment]
@TomSeldon - Did you get this working? I'm trying to do similar with a personal project here. https://github.com/MarcL/secure-redirects and running into the same issue.

**Comment by szarouski** [comment]
Same problem

**Comment by szarouski** [comment]
After I synced with repo (Settings => Resync with github) I don't get this error anymore.

**Comment by MarcL** [comment]
I've managed to get my `github` -> `travis` -> `coveralls` integration working now through trial and error but I still get the above error locally.

Not sure if this will help you @TomSeldon but my 2 scripts are:
```
    "coverage": "nyc report --reporter=text-lcov | coveralls",
    "test": "nyc --reporter=html --reporter=text mocha"
```
And Travis runs the `coverage` script in `after_success`.

**Comment by torinagrippa** [comment]
If you are using node.js, your Travis CI env variables may be missing the COVERALLS_REPO_TOKEN value.

**Comment by amalv** [comment]
In my case it was fixed adding the env variable as @torinagrippa suggested (using travis-ci.com)

**Comment by stevenvachon** [comment]
I've never had to add that env variable on Travis CI before and still don't, but adding it to AppVeyor CI fixed this issue.

**Comment by joscha** [comment]
references #997

**Comment by paras20xx** [comment]
This comment may help:
https://github.com/nickmerwin/node-coveralls/issues/166#issuecomment-387698861

**Comment by marinakr** [comment]
I get same error in elixir
https://travis-ci.org/edenlabllc/ds.api/jobs/506199980

**Comment by nickmerwin** [comment]
@marinakr could you re-run your build with the verbose flag so we can see exactly what's posting to Coveralls?

**Comment by marinakr** [comment]
https://travis-ci.org/edenlabllc/ds.api/jobs/506762479

**Comment by marinakr** [comment]
actually problem coveralls was not active in coveralls, problem was on my side

**Comment by marinakr** [comment]
https://travis-ci.org/edenlabllc/ds.api/jobs/506815647

**Comment by nickmerwin** [comment]
@marinakr ok it appears that empty data is being posted to Coveralls:

`{"git":{"branch":null},"service_job_id":null,"service_name":"travis-ci","source_files":[]}`
https://travis-ci.org/edenlabllc/ds.api/jobs/506815647#L3342

We need the `service_job_id` to find the project on Travis.

Can you re-check your configuration? Closing issue for now.
